apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: mysql
      image: mysql:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # Replace with a secure password
