apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: mysql
      image: 051034484218.dkr.ecr.us-east-1.amazonaws.com/clo835_sql:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # Replace with a secure password
