apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: mysql
      image: 835512929652.dkr.ecr.us-east-1.amazonaws.com/mysql-image-repo:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # Replace with a secure password
