apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: webapp
          image: 051034484218.dkr.ecr.us-east-1.amazonaws.com/clo835_app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.mysql.svc.cluster.local"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "rootpassword" 
            - name: DATABASE
              value: "employees"
            - name: DBPORT
              value: "3306"
            - name: APP_COLOR
              value: "lime" 
